### ISSUE TITLE
RAP dataset 

### ISSUE THREAD

**Issue by MoonBunnyZZZ** [fourierer/Pedestrian_Attribute_Recognition#1]
可以分享一下数据集吗，谢谢~ @fourierer

**Comment by fourierer** [comment]
> 可以分享一下数据集吗，谢谢~ @fourierer

链接: https://pan.baidu.com/s/19lSVnrZsjhlcc4813DltVQ  密码: 7ro3
设置的7天有效哈～

**Comment by MoonBunnyZZZ** [comment]
> > 可以分享一下数据集吗，谢谢~ @fourierer
> 
> 链接: https://pan.baidu.com/s/19lSVnrZsjhlcc4813DltVQ 密码: 7ro3
> 设置的7天有效哈～

多谢！

**Comment by MoonBunnyZZZ** [comment]
> > 可以分享一下数据集吗，谢谢~ @fourierer
> 
> 链接: https://pan.baidu.com/s/19lSVnrZsjhlcc4813DltVQ 密码: 7ro3
> 设置的7天有效哈～

 @fourierer 数据集和标注文件的解压密码求告知 ~~

**Comment by fourierer** [comment]
@MoonBunnyZZZ sry~时间长了都不记得这个数据集需要密码了，数据集和标签文件解压密码都是casia_cripac_isee_5610

**Comment by MoonBunnyZZZ** [comment]
> @MoonBunnyZZZ sry~时间长了都不记得这个数据集需要密码了，数据集和标签文件解压密码都是casia_cripac_isee_5610

@fourierer 太感谢你了。麻烦问下你有RAP2.0得数据么？我给官方发了邮件，还没得到答复

**Comment by fourierer** [comment]
@MoonBunnyZZZ sry~2.0木有

**Comment by MoonBunnyZZZ** [comment]
> @MoonBunnyZZZ sry~2.0木有

好的，谢谢

**Comment by xwf199** [comment]
请问可以分享一下数据集吗？感谢  @fourierer
